/*********************************************************************NVMH4****
Path:  SDK\DEMOS\common\inc\shared
File:  CgD3DSemantics.h

Copyright NVIDIA Corporation 2002
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
*AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA OR ITS SUPPLIERS
BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS)
ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.



Comments:

Defines register locations for DX HLSL & Cg hardware registers



******************************************************************************/

#ifndef __CG_D3D_SEMANTICS_H_
#define __CG_D3D_SEMANTICS_H_


// Vertex program varying inputs:
		// token			value			DX Semantic name
#define	CGDX8_POSITION		D3DVSDE_POSITION			/* POSITION		 */
#define	CGDX8_BLENDWEIGHT	D3DVSDE_BLENDWEIGHT			/* BLENDWEIGHT	 */
#define	CGDX8_NORMAL		D3DVSDE_NORMAL				/* NORMAL		 */	
#define	CGDX8_DIFFUSE		D3DVSDE_DIFFUSE				/* DIFFUSE		 */	
#define	CGDX8_SPECULAR		D3DVSDE_SPECULAR			/* SPECULAR		 */
#define	CGDX8_PSIZE			D3DVSDE_PSIZE				/* PSIZE		 */	
#define	CGDX8_BLENDINDICES	D3DVSDE_BLENDINDICES		/* BLENDINDICES	 */	
#define	CGDX8_TEXCOORD		D3DVSDE_TEXCOORD0			/* TEXCOORD		 */
#define	CGDX8_TEXCOORD0		D3DVSDE_TEXCOORD0			/* TEXCOORD0	 */	
#define	CGDX8_TEXCOORD1		D3DVSDE_TEXCOORD1			/* TEXCOORD1	 */	
#define	CGDX8_TEXCOORD2		D3DVSDE_TEXCOORD2			/* TEXCOORD2	 */	
#define	CGDX8_TEXCOORD3		D3DVSDE_TEXCOORD3			/* TEXCOORD3	 */
#define	CGDX8_TEXCOORD4		D3DVSDE_TEXCOORD4			/* TEXCOORD4	 */
#define	CGDX8_TEXCOORD5		D3DVSDE_TEXCOORD5			/* TEXCOORD5	 */
#define	CGDX8_TEXCOORD6		D3DVSDE_TEXCOORD6			/* TEXCOORD6	 */
#define	CGDX8_TEXCOORD7		D3DVSDE_TEXCOORD7			/* TEXCOORD7	 */
#define	CGDX8_TANGENT		D3DVSDE_POSITION2			/* TANGENT		 */
#define	CGDX8_BINORMAL		D3DVSDE_NORMAL2				/* BINORMAL		 */


//////////////////////////////////////////////////////////
// Macro for converting CGDX8_ values into vertex shader
//  input register tokens such as v1, v2, v9, etc.
// Use:  VIN( CGDX8_POSITION )  --> becomes v0

#define VIN( n )  v##n

//////////////////////////////////////////////////////////



#endif					// __CG_D3D_SEMANTICS_H_

