#define ID_HELPCONTEXT_DEFHELP  0
#define ID_HELPCONTEXT_APPABOUT 1
#define ID_HELPCONTEXT_USAGE    2

#define ID_HELPCONTEXT_INFINITEZOOM    10
#define ID_HELPCONTEXT_HAIR            11
#define ID_HELPCONTEXT_SOFTOBJETCS     12
#define ID_HELPCONTEXT_BEAMS           13
#define ID_HELPCONTEXT_DISPLACEMENTMAP 14
#define ID_HELPCONTEXT_OCEANSCENE      15
#define ID_HELPCONTEXT_VOLUMETRICLIGHT 16





