/*********************************************************************NVMH4****
Path:  SDK\MEDIA\programs\D3D9_FogPolygonVolumes
File:  Constants.h

Copyright NVIDIA Corporation 2002
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
*AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA OR ITS SUPPLIERS
BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS)
ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.



Comments:

******************************************************************************/



// For IM_Glow02
#define PCN_MULTFACTOR_0		0
#define PCN_MULTFACTOR_1		1
#define PCN_MULTFACTOR_2		2
#define PCN_MULTFACTOR_3		3


// for ps_2_0
#define CP_RGB_TEXADDR_WEIGHTS	4
#define CPN_RGB_TEXADDR_WEIGHTS	c4

////////////////////////////////////////////

#define	CV_CONSTS_1				 0


#define CV_WORLDVIEWPROJ_0		 2
#define CV_WORLDVIEWPROJ_1		 3
#define CV_WORLDVIEWPROJ_2		 4
#define CV_WORLDVIEWPROJ_3		 5


#define CV_PTS_BASE				10
//								11
//								12
//								13



#define CV_OBJ_AMBIENT_COL		20

#define CV_LIGHT_POS_OSPACE     21

#define CV_NDOTLTHRESH			25
#define CV_EXTRUSION_DIST		26


//@@@ rename inset distance
#define CV_FATNESS_SCALE        27



#define CV_BITREDUCE			30
#define CV_RAMPSCALE			31

#define	CV_RGB_TEXADDR_WEIGHTS	32
#define CV_DITHER_CONTROL		33


#define CV_DIRLIGHT1_DIR		40
#define CV_DIRLIGHT1_COLOR		41



#define	CV_HALF_TEXEL_SIZE		50


// For IM_Glow02
#define	CV_T0_OFFSET			60
#define	CV_T1_OFFSET			61
#define	CV_T2_OFFSET			62
#define	CV_T3_OFFSET			63











