MMwTempoMacro0(NOP		   )
MMwTempoMacro2(MOV			, RegDst, RegSrc)
MMwTempoMacro3(ADD			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(SUB			, RegDst, RegSrc, RegSrc)
MMwTempoMacro4(MAD			, RegDst, RegSrc, RegSrc, RegSrc)
MMwTempoMacro3(MUL			, RegDst, RegSrc, RegSrc)
MMwTempoMacro2(RCP			, RegDst, RegSrc)
MMwTempoMacro2(RSQ			, RegDst, RegSrc)
MMwTempoMacro3(DP3			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(DP4			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(MIN			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(MAX			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(SLT			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(SGE			, RegDst, RegSrc, RegSrc)
MMwTempoMacro2(EXP			, RegDst, RegSrc)
MMwTempoMacro2(LOG			, RegDst, RegSrc)
MMwTempoMacro2(LIT			, RegDst, RegSrc)
MMwTempoMacro3(DST			, RegDst, RegSrc, RegSrc)
MMwTempoMacro4(LRP			, RegDst, RegSrc, RegSrc, RegSrc)
MMwTempoMacro2(FRC			, RegDst, RegSrc)
MMwTempoMacro3(M4x4			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(M4x3			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(M3x4			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(M3x3			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(M3x2			, RegDst, RegSrc, RegSrc)
MMwTempoMacro1(CALL			, RegSrc)
MMwTempoMacro2(CALLNZ		, RegSrc, RegSrc)
MMwTempoMacro2(LOOP			, RegSrc, RegSrc)
MMwTempoMacro0(RET			)
MMwTempoMacro0(ENDLOOP      )
MMwTempoMacro1(LABEL		, RegSrc)
MMwTempoMacro3(POW			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(CRS			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(SGN			, RegDst, RegSrc, RegSrc)
MMwTempoMacro2(ABS			, RegDst, RegSrc)
MMwTempoMacro2(NRM			, RegDst, RegSrc)
MMwTempoMacro1(REP			, RegSrc)
MMwTempoMacro0(ENDREP       )
MMwTempoMacro1(IF			, RegSrc)
MMwTempoMacrN2(IFC, "if"	, RegSrc, RegSrc)
MMwTempoMacro0(ELSE         )
MMwTempoMacro0(ENDIF        )
MMwTempoMacro0(BREAK        )
MMwTempoMacrN2(BREAKC, "break", RegSrc, RegSrc)
MMwTempoMacro2(MOVA			, RegDst, RegSrc)
MMwTempoMacro2(DEFB			, RegDst, Bool)
MMwTempoMacro5(DEFI			, RegDst, Integer, Integer, Integer, Integer)

MMwTempoMacro1(TEXKILL		, RegSrc)
MMwTempoMacro2(TEXBEM		, RegDst, RegSrc)
MMwTempoMacro2(TEXBEML		, RegDst, RegSrc)
MMwTempoMacro2(TEXREG2AR	, RegDst, RegSrc)
MMwTempoMacro2(TEXREG2GB	, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x2PAD	, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x2TEX	, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x3PAD	, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x3TEX	, RegDst, RegSrc)
MMwTempoMacro3(TEXM3x3SPEC	, RegDst, RegSrc, RegSrc)
MMwTempoMacro2(TEXM3x3VSPEC	, RegDst, RegSrc)
MMwTempoMacro2(EXPP			, RegDst, RegSrc)
MMwTempoMacro2(LOGP			, RegDst, RegSrc)
MMwTempoMacro4(CND			, RegDst, RegSrc, RegSrc, RegSrc)
MMwTempoMacro5(DEF			, RegDst, Real, Real, Real, Real)
MMwTempoMacro2(TEXREG2RGB	, RegDst, RegSrc)
MMwTempoMacro2(TEXDP3TEX	, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x2DEPTH	, RegDst, RegSrc)
MMwTempoMacro2(TEXDP3		, RegDst, RegSrc)
MMwTempoMacro2(TEXM3x3		, RegDst, RegSrc)
MMwTempoMacro1(TEXDEPTH		, RegDst)
MMwTempoMacro4(CMP			, RegDst, RegSrc, RegSrc, RegSrc)
MMwTempoMacro3(BEM			, RegDst, RegSrc, RegSrc)
MMwTempoMacro4(DP2ADD		, RegDst, RegSrc, RegSrc, RegSrc)
MMwTempoMacro2(DSX			, RegDst, RegSrc)
MMwTempoMacro2(DSY			, RegDst, RegSrc)
MMwTempoMacro5(TEXLDD		, RegDst, RegSrc, RegSrc, RegSrc, RegSrc)
MMwTempoMacro3(SETP			, RegDst, RegSrc, RegSrc)
MMwTempoMacro3(TEXLDL		, RegDst, RegSrc, RegSrc)
MMwTempoMacro1(BREAKP		, RegSrc)

MMwTempoMacro0(PHASE        )