//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Meshuggah.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_DEMOMAINFRAME               129
#define IDD_SETUP                       130
#define IDR_CAPTUREMAINFRAME            130
#define IDD_SHADERFORMVIEW              131
#define IDD_INFINITE_ZOOM               132
#define IDD_HAIR                        133
#define IDI_EFFECT                      134
#define IDI_FOLDER                      135
#define IDI_FOLDER_OPEN                 136
#define IDI_EFFECT_PLAYING              137
#define IDI_INFO                        138
#define IDI_EFFECTSETTINGS              139
#define ID_VIEW_EFFECTSETTINGSDIALOG    140
#define IDD_SOFT_OBJECTS                141
#define IDI_HELP                        143
#define IDD_BEAMS                       144
#define IDD_DISPLACEMENTMAP             145
#define IDD_OCEANSCENE                  146
#define IDD_VOLUMETRICLIGHT             147
#define IDB_4FOLOGO                     148
#define IDB_PLEASEWAIT                  150
#define IDC_START_DEMO                  1001
#define IDC_DEMO                        1002
#define IDC_BROWSER                     1003
#define IDC_FULLSCREEN                  1006
#define IDC_TRIPLE_BUFFERING            1007
#define IDC_MUSIC                       1008
#define IDC_LOOP                        1009
#define IDC_640X480                     1010
#define IDC_800X600                     1011
#define IDC_1024X768                    1012
#define IDC_1152X864                    1013
#define IDC_1280X960                    1014
#define IDC_1280X1024                   1015
#define IDC_RESOLUTION_FRAME            1022
#define IDC_DEMOSETTINGS_FRAME          1023
#define IDC_LINK_ONION                  1024
#define IDC_LINK_4FO                    1025
#define IDC_SHADERTAB                   1026
#define IDC_PIXELSHADERFRAME            1027
#define IDC_VERTEXSHADERFRAME           1028
#define IDC_PIXELSHADEREDIT             1029
#define IDC_VERTEXSHADEREDIT            1030
#define IDC_VERSIONINFO                 1031
#define IDC_ZOOMPOS                     1032
#define IDC_ROTATEZ                     1033
#define IDC_ANIMATE                     1034
#define IDC_AMBIENT                     1037
#define IDC_DIFFUSE                     1038
#define IDC_GRIDSIZE                    1038
#define IDC_SPECULAR                    1039
#define IDC_GLOSS                       1040
#define IDC_DIFFUSE_COLOR               1041
#define IDC_SPECULAR_COLOR              1042
#define IDC_DIF_COLOR                   1043
#define IDC_DIFF_COLOR                  1043
#define IDC_SPEC_COLOR                  1044
#define IDC_NUM_SOFTOBJECTS             1045
#define IDC_THRESHOLD                   1046
#define IDC_ISOTHRESHOLD                1046
#define IDC_INERTIA                     1046
#define IDC_GRAVITY                     1047
#define IDC_HEIGHTSCALE                 1048
#define IDC_NUM_SOFTOBJECTS_EDIT        1049
#define IDC_GRIDSIZE_EDIT               1050
#define IDC_HEIGHTSCALE_EDIT            1050
#define IDC_ISOTHRESHOLD_EDIT           1051
#define IDC_DIFFUSE_EDIT                1051
#define IDC_SPECULAR_EDIT               1052
#define IDC_GLOSS_EDIT                  1053
#define IDC_GRAVITY_EDIT                1054
#define IDC_INERTIA_EDIT                1055
#define IDC_AMBIENT_EDIT                1056
#define IDC_WINDDIR                     1057
#define IDC_WINDDIR_EDIT                1058
#define IDC_WINDSPEED                   1059
#define IDC_WINDSPEED_EDIT              1060
#define IDC_WAVEHEIGHT                  1061
#define IDC_WAVEHEIGHT_EDIT             1062
#define IDC_DIRDEPENDENCE               1063
#define IDC_DIRDEPENDENCE_EDIT          1064
#define IDC_CHOPPYWAVES                 1065
#define IDC_CHOPPYWAVES_EDIT            1066
#define IDC_SUPPRESS_SMALLWAVES         1067
#define IDC_SUPPRESS_SMALLWAVES_EDIT    1068
#define IDC_NEWHEIGHTDATA               1069
#define IDC_DYNAMICRANGE                1070
#define IDC_DYNAMICRANGE_EDIT           1071
#define IDC_HTMLHELP                    1072
#define IDC_LINK_UPDATE                 1073
#define IDS_LINK_ONION                  61200
#define IDS_LINK_ONION_VISITED          61201
#define IDS_LINK_4FO                    61202
#define IDS_LINK_4FO_VISITED            61203
#define IDS_LINK_UPDATE                 61204
#define IDS_LINK_UPDATE_VISITED         61205
#define ID_FPS_INFO                     61206
#define ID_FPS                          61207
#define ID_REGISTRYKEY                  61208
#define IDS_D3D_NODX81                  61209
#define IDS_D3D_NODISPLAYMODES          61210
#define IDS_D3D_DISPENUMFAILED          61211
#define IDS_D3D_NO_ADAPTER_DISPLAYMODE  61212
#define IDS_D3D_NO_COLORBUFFER          61213
#define IDS_D3D_NO_SUITABLE_ZBUFFER     61214
#define IDS_ERROR_D3D                   61215
#define IDS_DEMOERROR_EFFECTSYSTEM      61216
#define IDS_BROWSERERROR_DATA           61217
#define IDS_BROWSERWARNING_NOHWVERTEXSHADER 61218

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
