//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ShaderX2MRT.rc
//
#define POWERVR_ICON                    101
#define ID_OPTIONS_FILTERING_POINTSAMPLING 40001
#define ID_OPTIONS_FILTERING_BILINEAR   40002
#define ID_OPTIONS_FILTERING_TRILINEAR  40003
#define ID_OPTIONS_FILTERING_ANISOTROPIC 40004
#define ID_OPTIONS_INFO                 40005
#define MENU_T_CAM                      40006
#define ID_OPTIONS_TOGGLECAMERA         40007
#define ID_OPTIONS_VISUALISEVOLUMES     40008
#define ID_OPTIONS_VIEWPOSITIONMRT      40009
#define ID_OPTIONS_VIEWNORMALMRT        40010
#define ID_OPTIONS_VIEWDIFFUSEMRT       40011
#define ID_OPTIONS_NORMAL               40012
#define MENU_T_VISVOL                   40013
#define ID_OPTIONS_VIEWTANGENTSPACE     40013
#define ID_OPTIONS_TEXTUREFORMAT_32BITS 40015
#define ID_OPTIONS_TEXTUREFORMAT_16BITS 40016
#define ID_OPTIONS_TEXTUREFORMAT_DXT    40017
#define ID_OPTIONS_SHADOWS              40018
#define ID_LIGHTS_CYCLINGLIGHTS         40020
#define ID_LIGHTS_FULLSCREENLIGHT       40021
#define ID_LIGHTS_SPHERELIGHT1          40022
#define ID_LIGHTS_SPHERELIGHT2          40023
#define ID_LIGHTS_CONELIGHT1            40024
#define ID_LIGHTS_CONELIGHT2            40025
#define ID_LIGHTS_CONELIGHT3            40026
#define ID_LIGHTS_CONELIGHT4            40027
#define ID_LIGHTS_CONELIGHT5            40028
#define ID_LIGHTS_CONELIGHT6            40029
#define ID_LIGHTS_ENABLEALLLIGHTS       40030
#define ID_LIGHTS_VIEWLIGHTZONES        40031
#define ID_OPTIONS_PAUSESTEP            40034
#define ID_OPTIONS_RESUME               40035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40036
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
